name: Twitter to Telegram Auto

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.CHAT_ID }}" \
            -d "text=🚀 *JUGAAD Bot is LIVE* ✅%0A%0A📢 Latest tweet from @${{ secrets.SCREEN_NAME }}%0A%0A🔗 https://twitter.com/${{ secrets.SCREEN_NAME }}%0A%0A🏷️ #JUGAAD #Solana" \
            -d "parse_mode=Markdown"
